SITES = [["7th-Circle Pyrite",
  "https://www.7thcirclepyrite.com/submissions",
  "fantasy, mystical, <2500, ¢"],
 ["Adventitious",
  "https://www.adventitious.net/submission-guidelines/",
  "sf, fantasy, flash <1k, <17k, 5808$"],
 ["After the Storm",
  "https://medium.com/after-the-storm/submission-guide-for-after-the-storm-472ac07eb0e7",
  "sf, fantasy, anti-capitalist, 1000-5000, €, medium 403"],
 ["Allegory",
  "https://www.allegoryezine.com/submissions",
  "sf, fantasy, horror, <5000, $"],
 ["Altered Reality", "https://www.alteredrealitymag.com/", "sf, fantasy, ¢"],
 ["Analog",
  "https://analogsf.com/contact-us/writers-guidelines/",
  "sf, ugh, €€€"],
 ["Andromeda Spaceways",
  "https://andromedaspaceways.com/submissions-manager/",
  "sf, fantasy, horror, $"],
 ["AntipodeanSF",
  "https://www.antisf.com.au/submission-guidelines",
  "flash, sf, fantasy, australian, twists, <1000, ¢"],
 ["Apex Magazine",
  "https://www.apexbookcompany.com/a/blog/apex-magazine/post/apex-magazine-submissions-guidelines",
  "flash 💚?, sf, fantasy, horror, $$$"],
 ["Apparition Lit",
  "https://apparitionlit.com/submissions/",
  "flash, $$, <5000"],
 ["Arcturus",
  "https://arcturusmag.com/submit/",
  "flash, sf, fantasy, <5000, ¢"],
 ["Asimov Press", "https://press.asimov.com/about", "sf, science focus, $$$"],
 ["Asimov's",
  "https://asimovs.com/contact-us/writers-guidelines/",
  "sf, 1000-20k, ugh, €€€"],
 ["Augur", "https://augursociety.org/submissions/", "sf, fantasy, $$$"],
 ["Aurealis", "https://aurealis.com.au/submissions/", "sf, australian, $$"],
 ["Baffling Magazine",
  "https://www.bafflingmag.com/submissions",
  "sf, fantasy, <1200, queer, $$$"],
 ["Belladonna's Garden",
  "https://www.belladonnasgardenlit.com/submissions",
  "gentle, fantasy, themed, flash, <5000, ¢"],
 ["Beneath Ceaseless Skies",
  "https://www.beneath-ceaseless-skies.com/submissions/",
  "fantasy, <15000, $$$"],
 ["Bewildering Stories",
  "https://www.bewilderingstories.com/submissions.html",
  "sf, fantasy, flash, ¢"],
 ["BFS Horizons",
  "https://britishfantasysociety.org/get-in-touch/bfs-horizons/",
  "fantasy, horror, <5000, $"],
 ["Black Cat Weekly",
  "https://wildside.moksha.io/publication/black-cat-weekly-science-fiction/guidelines",
  "sf, fantasy, $"],
 ["Black Hare Press",
  "https://blackharepress.com/blogs/open-calls",
  "sf, fantasy, dark, <2000, $"],
 ["Blue Earth Review",
  "https://blueearthreview.submittable.com/submit",
  "sf, fantasy, <4000, ¢"],
 ["Bottleneck",
  "https://www.bottleneck-sf.com/submission-guidelines",
  "sf, fantasy, 3000-8000, ¢"],
 ["Bourbon Penn",
  "https://www.bourbonpenn.com/submissions",
  "odd, surreal, $$"],
 ["Carnage House",
  "https://carnagehouse.com/submission/subs.php",
  "horror, 500-5500, $"],
 ["Clarkesworld",
  "https://clarkesworldmagazine.com/submissions/",
  "sf, fantasy, 1000-22000, $$$"],
 ["CommuterLit",
  "https://commuterlit.com/for-writers/submission-guidelines/",
  "sf, fantasy, 500-4000, ¢"],
 ["Corner Bar Magazine", "http://www.cornerbarmagazine.com/how.html", "sf, ¢"],
 ["Cosmic Horror Monthly",
  "https://cosmichorrormonthly.com/submissions/",
  "$, horror, cosmic, 1/1-7, 7/1-7"],
 ["Creation Magazine",
  "https://sites.google.com/creationmag.org/creationmag/submit",
  "sf, fantasy, horror, <5000, ¢"],
 ["Crepuscular Magazine",
  "https://www.patreon.com/posts/submission-85137677",
  "sf, fantasy, horror <250, ¢"],
 ["Crow & Cross Keys",
  "https://crowcrosskeys.com/submit/",
  "sf, fantasy, folk, flash, <5000, ¢"],
 ["Daily Science Fiction", "https://dailysciencefiction.com/", "flash, €?"],
 ["Del Sol Review",
  "https://delsolreview.webdelsol.com/guidelines.htm",
  "sf, fantasy, 300-5000, ¢"],
 ["Diabolical Plots",
  "https://www.diabolicalplots.com/guidelines/",
  "sf, fantasy, $$$"],
 ["DreamForge",
  "https://dreamforgemagazine.com/for-authors/call-for-submissions/",
  "$$$, <7000"],
 ["Ecological Citizen",
  "https://ecologicalcitizen.net/submitting-fiction.html",
  "sf, eco, <2000, ¢"],
 ["Eldritch Science", "https://tnfff.org/submissions/", "sf, ¢"],
 ["Electric Spec",
  "https://www.electricspec.com/Submissions.html",
  "sf, fantasy, horror, <7000, $"],
 ["Escape Pod",
  "https://escapepod.org/guidelines/short-fiction/",
  "podcast, <6000, sf, $$$"],
 ["Every Day Fiction",
  "https://everydayfiction.com/submit-story/",
  "flash, $"],
 ["F(r)iction",
  "https://frictionlit.org/about/submit/",
  "flash, weird, $, fee"],
 ["Factor Four Magazine",
  "https://factorfourmag.com/submissionsinfo/",
  "sf, fantasy, horror, <1000, flash, $$$"],
 ["Fantasy & Science Fiction",
  "https://www.fandsf.com/glines.htm",
  "sf, fantasy, <25k, ugh, €€€"],
 ["Fantasy Magazine",
  "https://psychopomp.com/fantasy-magazine-guidelines/",
  "fantasy, flash < 1500, shorts < 5k, $"],
 ["Farthest Star Publishing",
  "https://www.fartheststarpublishing.com/general-8",
  "sf, fantasy, novelette, 8000-17000, $"],
 ["Five on the Fifth",
  "https://fiveonthefifth.submittable.com/submit",
  "horror, flash, ¢"],
 ["Flash Point Science Fiction",
  "https://flashpointsf.com/submissions/",
  "sf, fantasy, <1000, $"],
 ["Free Flash Fiction",
  "https://freeflashfiction.com/submissions/",
  "sf, fantasy, horror, flash, <500, ¢"],
 ["Freedom Fiction Journal",
  "https://www.freedomfiction.com/submissions/",
  "sf, fantasy, flash <500, 1000-12000, ¢"],
 ["Fusion Fragment", "https://www.fusionfragment.com/submissions/", "sf, $$"],
 ["Galaxy's Edge", "https://www.galaxysedge.com/submissions/", "sf, $$$"],
 ["Gavagai",
  "https://gavagai.com/submit/quick",
  "spec, ~2k, 5808$, login req."],
 ["GigaNotoSaurus",
  "https://giganotosaurus.org/submission-guidelines/",
  "$$$, 5000-25k"],
 ["Harvey Duckman",
  "https://harvey-duckman-is-alive.ghost.io/submissions/",
  "sf, fantasy, $"],
 ["Haven Speculative",
  "https://www.havenspec.com/submit/",
  "sf, fantasy, <6000, $$"],
 ["Havok",
  "https://gohavok.com/submission-guidelines/",
  "sf, fantasy, themed, flash, 300-1000, ¢"],
 ["Hawthorn & Ash",
  "https://ironfaeriepublishing.com/hawthorn-ash/",
  "fantasy, horror, flash <1000, $"],
 ["Howdy Dude Paperbacks",
  "https://howdydudepaperbacks.com/submissions/",
  "sf, 2000-8000, $"],
 ["Hyphen Punk", "https://hyphenpunk.com/submissions/", "punk, 1000-7500, $"],
 ["Incensepunk",
  "https://www.incensepunk.com/p/submissions",
  "sf, religous, $$"],
 ["Interzone", "https://interzone.press/submissions/", "sf, <17500, $$"],
 ["Intrepidus Ink",
  "https://intrepidusink.com/submissions/",
  "sf, fantasy, flash <1000, <2500, $"],
 ["James Gunn's Ad Astra",
  "https://www.adastrasf.com/submissions/short-fiction-submission-guidelines/",
  "sf, fantasy, <7500, $"],
 ["Kismet", "https://thekismetmagazine.com/submit/", "sf, fantasy, <10000, ¢"],
 ["Lady Churchill’s Rosebud Wristlet",
  "https://smallbeerpress.com/about/submission-guidelines/",
  "sf, <40k, $$"],
 ["Lightspeed",
  "https://adamant.moksha.io/publication/lightspeed",
  "sf, fantasy, 1500-10k, <5k pref, $$$"],
 ["Little Blue Marble",
  "https://littlebluemarble.ca/submission-guidelines/",
  "ecological, optimistic, <2000, €€€"],
 ["Lost Colony",
  "https://lostcolonymagazine.com/submissions/",
  "sf, 10k-25k, €"],
 ["Manawaker Flash Fiction Podcast",
  "https://www.manawaker.com/ffp-submissions/",
  "sf, flash <1000, $"],
 ["Moonday Mag",
  "https://moondaymag.com/submissions",
  "sf, fantasy, <4000, ¢"],
 ["Moonpark Review",
  "https://moonparkreview.com/submission-guidelines/",
  "speculative, flash, <750, ¢"],
 ["Mystic Mind",
  "https://kirincomicscontact.wixsite.com/my-site/about-1",
  "sf, fantasy, <5000, $"],
 ["Mythaxis",
  "https://mythaxis.co.uk/submissions.html",
  "flash (500-2k), 2000-5000, $"],
 ["Nature: Futures",
  "https://www.nature.com/nature/for-authors/other-subs",
  "sf, hard, 850-950, $$$"],
 ["Necessary Fiction",
  "https://necessaryfiction.submittable.com/submit",
  "sf, fantasy, ¢"],
 ["Neon Dystopia",
  "https://www.neondystopia.com/?p=100042814",
  "sf, cyberpunk, $"],
 ["New Edge Sword & Sorcery",
  "https://newedgeswordandsorcery.com/submissions/",
  "s&s, 4000-6000, $$"],
 ["New Maps",
  "https://www.new-maps.com/submissions/",
  "sf, deindustrial, <10000, $"],
 ["new sinews", "https://www.newnewsinews.com/about", "sf, ¢"],
 ["Nightmare",
  "https://adamant.moksha.io/publication/nightmare/guidelines",
  "horror, $$$"],
 ["Not One of Us",
  "https://legacyliteraryservices.com/not-one-of-us/",
  "sf, alienation, $"],
 ["Old Moon",
  "https://www.oldmoonpublishing.com/submissions",
  "s&s, weird, 1000-10k, $$$"],
 ["Orion's Belt", "https://www.orions-belt.net/submissions", "sf, <1200, $"],
 ["Penumbric",
  "https://www.penumbric.com/subs.html",
  "sf, fantasy, horror, edgy, $"],
 ["Phano", "https://www.phano.co/submissions", "sf, <5000, $"],
 ["PodCastle",
  "https://podcastle.org/guidelines/",
  "podcast, <6000, fantasy, $$$"],
 ["Possibilia",
  "https://www.futureaesthetics.foundation/post/how-to-submit-work-to-possibilia-magazine",
  "sf, 3000-7000, idea first?, ¢"],
 ["Propagule",
  "https://www.propagule.co/#w-tabs-2-data-w-pane-2",
  "sf, <10000, $"],
 ["Pseudopod",
  "https://pseudopod.org/submissions/",
  "podcast, <6000, horror, $$$"],
 ["Psychopomp Novellas",
  "https://psychopomp.com/novella-guidelines/",
  "novellas, €"],
 ["Pulp Asylum",
  "https://www.pulpasylum.com/guidelines.html",
  "sf, fantasy, <3000, $"],
 ["Radon Journal", "https://www.radonjournal.com/submit", "sf, <5000, $"],
 ["Razzle Dazzle Cafe",
  "https://razzledazzlecafe.substack.com/p/submission-guidelines",
  "sf, 1000-2000, ¢"],
 ["Reckoning",
  "https://reckoning.press/submit/fiction/",
  "sf, environmental, <15000, $$$"],
 ["Renaissance Review",
  "https://renaissancerev.weebly.com/submit.html",
  "sf, <5000, ¢"],
 ["Roi Fainéant", "https://www.roifaineantpress.com/submissions-1", "sf, ¢"],
 ["Seize the Press",
  "https://www.seizethepress.com/submissions/",
  "sf, anticapitalist, $"],
 ["Shoreline of Infinity",
  "https://www.shorelineofinfinity.com/submissions/",
  "sf, $$"],
 ["Slipjack Review",
  "https://skipjackreview.com/submit/",
  "sf, eclectic, <5000, ¢"],
 ["Small Wonders",
  "https://smallwondersmag.com/submissions/",
  "flash, <1000, $$$"],
 ["Solarpunk Magazine",
  "https://solarpunkmagazine.com/submissions/",
  "solarpunk, 1500-7500, $$$"],
 ["StarShipSofa",
  "http://www.starshipsofa.com/submissions/",
  "sf, 3000-7000, $"],
 ["State of Matter",
  "https://stateofmatter.in/submissions/",
  "sf, 1000-15000, ¢"],
 ["Story Bottle",
  "https://www.storybottleco.org/submissions",
  "sf, flash <1500, <8000, ¢"],
 ["Strange Horizons",
  "http://strangehorizons.com/submit/fiction-submission-guidelines/",
  "sf, fantasy, <10k 5k pref, $$$"],
 ["Stupefying Stories",
  "https://stupefyingstories.blogspot.com/p/submission-guidelines_1.html",
  "sf, €"],
 ["swamp pink", "https://swamp-pink.charleston.edu/submit/", "sf, $$"],
 ["Tales & Feathers",
  "https://augursociety.org/submissions/",
  "fantasy, cozy, $$$"],
 ["Tales from the Crosstimbers",
  "https://thecrosstimbers.net/author-guidelines/",
  "sf, 1000-2500, $"],
 ["Tall Tale TV",
  "https://talltaletv.com/submission-guidelines/",
  "sf, fantasy, <6000, $"],
 ["Tamarind", "https://tamarindlit.co.uk/submissions/", "sf, 1500-5000, ¢"],
 ["The Bizarchives",
  "https://thebizarchives.com/submissions/",
  "sf, fantasy, weird, dark, ¢"],
 ["The Canadian Sepulchral",
  "https://joewiwcharuk.wixsite.com/the-canadian-sepulch/submissions",
  "horror, canadian, 1000-5000, ¢"],
 ["The Colored Lens",
  "https://thecoloredlens.com/?page_id=137752",
  "sf, fantasy, 500-5000, $"],
 ["The Daily Tomorrow",
  "https://www.thedailytomorrow.com/submissions",
  "sf, 2100-3500, serial, ¢"],
 ["The Dark",
  "https://www.thedarkmagazine.com/submission-guidelines/",
  "horror, dark fantasy, 2000-6000, $$"],
 ["The Deadlands",
  "https://psychopomp.com/the-deadlands-guidelines/",
  "sf, fantasy, horror, anthology, €"],
 ["The Fabulist",
  "https://fabulistmagazine.com/short-fiction-guidelines/",
  "sf, fantasy, $$"],
 ["The Future Fire",
  "https://futurefire.net/guidelines/fiction.html",
  "sf, social, flash <1000, <17000, $"],
 ["The Genre Society",
  "https://www.thegenresociety.com/submissions",
  "sf, fantasy, horror, ¢"],
 ["The Hooklet's Nook",
  "https://www.thehooletsnook.com/submissions.html",
  "sf, fantasy, flash, <300, ¢"],
 ["The Horror Zine",
  "https://www.thehorrorzine.com/Submission%20Guidelines.html",
  "horror, sf, fantasy, 1900-4000, ¢"],
 ["The Lit Nerds", "https://thelitnerds.com/submit/", "sf, fantasy, <3000, ¢"],
 ["The Piker Press", "https://www.pikerpress.com/", "sf, horror, <10000, ¢"],
 ["Third Flatiron",
  "https://thirdflatiron.com/?page_id=13",
  "anthology, $$$, 1500-3000"],
 ["Three-Lobed Burning Eye",
  "https://www.3lobedmag.com/submissions.html",
  "sf, dark fantasy, horror, $$$"],
 ["Timber Ghost",
  "https://www.timberghostpress.com/submissions.html#/",
  "horror, flash <1000, $"],
 ["Translunar Travelers Lounge",
  "https://translunartravelerslounge.com/submissions/",
  "$, <5000, 3/15-4/15, 9/15-10/15"],
 ["Trembling with Fear",
  "https://horrortree.com/submissions/",
  "horror, €, 403 on Actions"],
 ["Trollbreath", "https://magazine.trollbreath.com/submissions/", "<7500, $$"],
 ["Uncanny",
  "https://www.uncannymagazine.com/submissions/",
  "sf, 750-10000, €€, 403 on Actions"],
 ["Untold Tales",
  "https://www.podpage.com/untold-tales/p/submissions/",
  "sf, fantasy, horror, 2000-5500, ¢"],
 ["Utopia Science Fiction",
  "https://www.utopiasciencefiction.com/submit",
  "sf, <4000, $$$"],
 ["Weird Tales", "https://www.weirdtales.com/submissions", "sf, €"],
 ["White Cat Publications",
  "https://whitecatpublications.com/guidelines/",
  "sf, <2500, $"],
 ["Worlds of If", "https://worldsofifmagazine.com/submissions", "sf, €"],
 ["Worlds of Possibility",
  "https://worldsofpossibility.moksha.io/closed",
  "sf, fantasy, €"]]
