name: Update the submissions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - run: |
          env
          ./update-submissions
          git config --global user.name 'Jason R. Clark'
          git config --global user.email 'jason@jasonrclark.net'
          git add README.md
          git commit -m "Updated submissions"
          git push origin main
